version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/shorturlapp/back
file_exists_behavior: OVERWRITE

permissions:
  -object: /home/ubuntu/shorturlapp
  owner: ubuntu
  group: ubuntu

hooks:
  AfterInstall:
    -location: after-deploy.sh
    timeout: 2000
    runas: root
#별도 확인 요망!!!!!!!!! 마지막!!!!