version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/shorturlapp
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/apps/shorturlapp
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: after-deploy.sh
      timeout: 2000
      runas: root
