spring:
  datasource:
    jdbc-url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
