spring:
  datasource:
    jdbc-url: ${{ secrets.DB_URL }}
    username: ${{ secrets.DB_ID }}
    password: ${{ secrets.DB_PW }}
    driver-class-name: org.mariadb.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
