name: Deploy workflow on production environment

on:
  pull_request:
      branches: [main]
      types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: BE

    steps:
      - name: Checkout Github-Action
        uses: actions/checkout@v3

      - name: java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: gradlew
        run: chmod +x ./gradlew

      - name: Gradle build
        run: ./gradlew build

  deploy:
    needs: build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Zip project files
        run: zip -r ./$GITHUB_SHA.zip .

      - name: Access to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETEKEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.S3_BUCKET_DIR_NAME }}/$GITHUB_SHA.zip

      - name: Deploy to EC2 with CodeDeploy
        run: aws deploy create-deployment
            --application-name codedeploy-app
            --deployment-config-name CodeDeployDefault.AllAtOnce
            --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP_NAME }}
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=${{ secrets.S3_BUCKET_DIR_NAME }}/$GITHUB_SHA.zip
